export const LOAD_CASHOUT_REQ_LIST_REQUEST = "LOAD_CASHOUT_REQ_LIST_REQUEST";
export const LOAD_CASHOUT_REQ_LIST_SUCCESS = "LOAD_CASHOUT_REQ_LIST_SUCCESS";
export const LOAD_CASHOUT_REQ_LIST_FAIL = "LOAD_CASHOUT_REQ_LIST_FAIL";

export const LOAD_CASHOUT_APPROVAL_LIST_REQUEST = "LOAD_CASHOUT_APPROVAL_LIST_REQUEST";
export const LOAD_CASHOUT_APPROVAL_LIST_SUCCESS = "LOAD_CASHOUT_APPROVAL_LIST_SUCCESS";
export const LOAD_CASHOUT_APPROVAL_LIST_FAIL = "LOAD_CASHOUT_APPROVAL_LIST_FAIL";

export const LOAD_CASHOUT_DISBURSE_LIST_REQUEST = "LOAD_CASHOUT_DISBURSE_LIST_REQUEST";
export const LOAD_CASHOUT_DISBURSE_LIST_SUCCESS = "LOAD_CASHOUT_DISBURSE_LIST_SUCCESS";
export const LOAD_CASHOUT_DISBURSE_LIST_FAIL = "LOAD_CASHOUT_DISBURSE_LIST_FAIL";

export const LOAD_CASHOUT_DECLINE_LIST_REQUEST = "LOAD_CASHOUT_DECLINE_LIST_REQUEST";
export const LOAD_CASHOUT_DECLINE_LIST_SUCCESS = "LOAD_CASHOUT_DECLINE_LIST_SUCCESS";
export const LOAD_CASHOUT_DECLINE_LIST_FAIL = "LOAD_CASHOUT_DECLINE_LIST_FAIL";

export const APPROVE_CASHOUT_REQ_REQUEST = "APPROVE_CASHOUT_REQ_REQUEST";
export const APPROVE_CASHOUT_REQ_SUCCESS = "APPROVE_CASHOUT_REQ_SUCCESS";
export const APPROVE_CASHOUT_REQ_FAIL = "APPROVE_CASHOUT_REQ_FAIL";
export const APPROVE_CASHOUT_REQ_RESET = "APPROVE_CASHOUT_REQ_RESET";

export const DECLINE_CASHOUT_REQ_REQUEST = "DECLINE_CASHOUT_REQ_REQUEST";
export const DECLINE_CASHOUT_REQ_SUCCESS = "DECLINE_CASHOUT_REQ_SUCCESS";
export const DECLINE_CASHOUT_REQ_FAIL = "DECLINE_CASHOUT_REQ_FAIL";
export const DECLINE_CASHOUT_REQ_RESET = "DECLINE_CASHOUT_REQ_RESET";

export const DISBURSE_CASHOUT_REQ_REQUEST = "DISBURSE_CASHOUT_REQ_REQUEST";
export const DISBURSE_CASHOUT_REQ_SUCCESS = "DISBURSE_CASHOUT_REQ_SUCCESS";
export const DISBURSE_CASHOUT_REQ_FAIL = "DISBURSE_CASHOUT_REQ_FAIL";
export const DISBURSE_CASHOUT_REQ_RESET = "DISBURSE_CASHOUT_REQ_RESET";

export const CREATE_CASHOUT_OPTION_REQUEST = "CREATE_CASHOUT_OPTION_REQUEST";
export const CREATE_CASHOUT_OPTION_SUCCESS = "CREATE_CASHOUT_OPTION_SUCCESS";
export const CREATE_CASHOUT_OPTION_FAIL = "CREATE_CASHOUT_OPTION_FAIL";
export const CREATE_CASHOUT_OPTION_RESET = "CREATE_CASHOUT_OPTION_RESET";

export const LOAD_CASHOUT_OPTION_LIST_REQUEST = "LOAD_CASHOUT_OPTION_LIST_REQUEST";
export const LOAD_CASHOUT_OPTION_LIST_SUCCESS = "LOAD_CASHOUT_OPTION_LIST_SUCCESS";
export const LOAD_CASHOUT_OPTION_LIST_FAIL = "LOAD_CASHOUT_OPTION_LIST_FAIL";

export const DELETE_CASHOUT_OPTION_REQUEST = "DELETE_CASHOUT_OPTION_REQUEST";
export const DELETE_CASHOUT_OPTION_SUCCESS = "DELETE_CASHOUT_OPTION_SUCCESS";
export const DELETE_CASHOUT_OPTION_FAIL = "DELETE_CASHOUT_OPTION_FAIL";
export const DELETE_CASHOUT_OPTION_RESET = "DELETE_CASHOUT_OPTION_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
