export const LOAD_DASHBOARD_REQUEST = "LOAD_DASHBOARD_REQUEST";
export const LOAD_DASHBOARD_SUCCESS = "LOAD_DASHBOARD_SUCCESS";
export const LOAD_DASHBOARD_FAIL = "LOAD_DASHBOARD_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
