export const LOAD_OFFER_REQUEST = "LOAD_OFFER_REQUEST";
export const LOAD_OFFER_SUCCESS = "LOAD_OFFER_SUCCESS";
export const LOAD_OFFER_FAIL = "LOAD_OFFER_FAIL";

export const CREATE_OFFER_REQUEST = "CREATE_OFFER_REQUEST";
export const CREATE_OFFER_SUCCESS = "CREATE_OFFER_SUCCESS";
export const CREATE_OFFER_FAIL = "CREATE_OFFER_FAIL";
export const CREATE_OFFER_RESET = "CREATE_OFFER_RESET";

export const APPROVE_OFFER_REQUEST = "APPROVE_OFFER_REQUEST";
export const APPROVE_OFFER_SUCCESS = "APPROVE_OFFER_SUCCESS";
export const APPROVE_OFFER_FAIL = "APPROVE_OFFER_FAIL";
export const APPROVE_OFFER_RESET = "APPROVE_OFFER_RESET";

export const DECLINE_OFFER_REQUEST = "DECLINE_OFFER_REQUEST";
export const DECLINE_OFFER_SUCCESS = "DECLINE_OFFER_SUCCESS";
export const DECLINE_OFFER_RESET = "DECLINE_OFFER_RESET";
export const DECLINE_OFFER_FAIL = "DECLINE_OFFER_FAIL";

export const LOAD_OFFER_DETAILS_REQUEST = "LOAD_OFFER_DETAILS_REQUEST";
export const LOAD_OFFER_DETAILS_SUCCESS = "LOAD_OFFER_DETAILS_SUCCESS";
export const LOAD_OFFER_DETAILS_FAIL = "LOAD_OFFER_DETAILS_FAIL";

export const UPDATE_OFFER_REQUEST = "UPDATE_OFFER_REQUEST";
export const UPDATE_OFFER_SUCCESS = "UPDATE_OFFER_SUCCESS";
export const UPDATE_OFFER_FAIL = "UPDATE_OFFER_FAIL";
export const UPDATE_OFFER_RESET = "UPDATE_OFFER_RESET";

export const DELETE_OFFER_REQUEST = "DELETE_OFFER_REQUEST";
export const DELETE_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS";
export const DELETE_OFFER_RESET = "DELETE_OFFER_RESET";
export const DELETE_OFFER_FAIL = "DELETE_OFFER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
