export const LOAD_ALL_SETTINGS_REQUEST = "LOAD_ALL_SETTINGS_REQUEST";
export const LOAD_ALL_SETTINGS_SUCCESS = "LOAD_ALL_SETTINGS_SUCCESS";
export const LOAD_ALL_SETTINGS_FAIL = "LOAD_ALL_SETTINGS_FAIL";

export const TOGGLE_LOUNGE_MEETING_REQUEST = "TOGGLE_LOUNGE_MEETING_REQUEST";
export const TOGGLE_LOUNGE_MEETING_SUCCESS = "TOGGLE_LOUNGE_MEETING_SUCCESS";
export const TOGGLE_LOUNGE_MEETING_FAIL = "TOGGLE_LOUNGE_MEETING_FAIL";
export const TOGGLE_LOUNGE_MEETING_RESET = "TOGGLE_LOUNGE_MEETING_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";