export const LOAD_SPECIAL_DAY_REQUEST = "LOAD_SPECIAL_DAY_REQUEST";
export const LOAD_SPECIAL_DAY_SUCCESS = "LOAD_SPECIAL_DAY_SUCCESS";
export const LOAD_SPECIAL_DAY_FAIL = "LOAD_SPECIAL_DAY_FAIL";

export const CREATE_SPECIAL_DAY_REQUEST = "CREATE_SPECIAL_DAY_REQUEST";
export const CREATE_SPECIAL_DAY_SUCCESS = "CREATE_SPECIAL_DAY_SUCCESS";
export const CREATE_SPECIAL_DAY_FAIL = "CREATE_SPECIAL_DAY_FAIL";
export const CREATE_SPECIAL_DAY_RESET = "CREATE_SPECIAL_DAY_RESET";

export const SEND_SPECIAL_DAY_REQUEST = "SEND_SPECIAL_DAY_REQUEST";
export const SEND_SPECIAL_DAY_SUCCESS = "SEND_SPECIAL_DAY_SUCCESS";
export const SEND_SPECIAL_DAY_FAIL = "SEND_SPECIAL_DAY_FAIL";
export const SEND_SPECIAL_DAY_RESET = "SEND_SPECIAL_DAY_RESET";

export const DELETE_SPECIAL_DAY_REQUEST = "DELETE_SPECIAL_DAY_REQUEST";
export const DELETE_SPECIAL_DAY_SUCCESS = "DELETE_SPECIAL_DAY_SUCCESS";
export const DELETE_SPECIAL_DAY_RESET = "DELETE_SPECIAL_DAY_RESET";
export const DELETE_SPECIAL_DAY_FAIL = "DELETE_SPECIAL_DAY_FAIL";

export const UPDATE_SPECIAL_DAY_REQUEST = "UPDATE_SPECIAL_DAY_REQUEST";
export const UPDATE_SPECIAL_DAY_SUCCESS = "UPDATE_SPECIAL_DAY_SUCCESS";
export const UPDATE_SPECIAL_DAY_FAIL = "UPDATE_SPECIAL_DAY_FAIL";
export const UPDATE_SPECIAL_DAY_RESET = "UPDATE_SPECIAL_DAY_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
